// client-angular/src/app/chat/components/chat-window/chat-window.component.ts
import {
  Component,
  Input,
  OnInit,
  OnDestroy,
  OnChanges,
  SimpleChanges,
  ViewChild,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject } from 'rxjs';
import { takeUntil, debounceTime, switchMap, filter } from 'rxjs/operators';

import { ChatApiService } from '../../services/chat-api.service';
import { ChatSocketService } from '../../services/chat-socket.service';
import { ChatUser, ChatMessage, Conversation } from '../../models/chat.models';
import { avatarColor } from '../../services/avatar.util';

import { MessageBubbleComponent } from '../message-bubble/message-bubble.component';
import { MentionDropdownComponent } from '../mention-dropdown/mention-dropdown.component';

@Component({
  selector: 'cflow-chat-window',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MessageBubbleComponent,
    MentionDropdownComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './chat-window.component.html',
  styleUrls: ['./chat-window.component.css'],
})
export class ChatWindowComponent implements OnInit, OnDestroy, OnChanges {
  // ── Inputs (provided by the host Cflow page) ──────────
  @Input() workflowId!: string;
  @Input() currentUser!: ChatUser;

  // ── Template refs ─────────────────────────────────────
  @ViewChild('scrollContainer') scrollContainer!: ElementRef<HTMLDivElement>;
  @ViewChild('messageInput') messageInput!: ElementRef<HTMLTextAreaElement>;

  // ── State ─────────────────────────────────────────────
  conversation: Conversation | null = null;
  messages: ChatMessage[] = [];
  inputText = '';
  loading = true;
  typingUsers: Map<string, string> = new Map(); // user_id → name

  // Mentions
  mentionResults: ChatUser[] = [];
  mentionIndex = 0;
  showMentions = false;

  private destroy$ = new Subject<void>();
  private mentionSearch$ = new Subject<string>();
  private typingTimeout: ReturnType<typeof setTimeout> | null = null;

  constructor(
    private api: ChatApiService,
    private socket: ChatSocketService,
    private cdr: ChangeDetectorRef
  ) {}

  // ── Lifecycle ─────────────────────────────────────────

  ngOnInit(): void {
    this.setupMentionSearch();
    this.loadChat();
  }

  ngOnChanges(changes: SimpleChanges): void {
    // Reload if workflowId or user changes
    if (
      (changes['workflowId'] && !changes['workflowId'].firstChange) ||
      (changes['currentUser'] && !changes['currentUser'].firstChange)
    ) {
      this.socket.disconnect();
      this.messages = [];
      this.conversation = null;
      this.loading = true;
      this.cdr.markForCheck();
      this.loadChat();
    }
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    this.socket.disconnect();
    if (this.typingTimeout) clearTimeout(this.typingTimeout);
  }

  // ── Data loading ──────────────────────────────────────

  private loadChat(): void {
    this.api.getConversation(this.workflowId).subscribe({
      next: (convo) => {
        this.conversation = convo;
        this.loadMessages(convo.id);
        this.connectSocket();
      },
      error: (err) => {
        console.error('[Chat] Failed to load conversation:', err);
        this.loading = false;
        this.cdr.markForCheck();
      },
    });
  }

  private loadMessages(conversationId: string): void {
    this.api.getMessages(conversationId).subscribe({
      next: (msgs) => {
        this.messages = msgs;
        this.loading = false;
        this.cdr.markForCheck();
        this.scrollToBottom();
      },
      error: (err) => {
        console.error('[Chat] Failed to load messages:', err);
        this.loading = false;
        this.cdr.markForCheck();
      },
    });
  }

  // ── Socket connection ─────────────────────────────────

  private connectSocket(): void {
    this.socket.connect(this.workflowId, this.currentUser);

    this.socket.message$.pipe(takeUntil(this.destroy$)).subscribe((msg) => {
      // Deduplicate
      if (!this.messages.some((m) => m.id === msg.id)) {
        this.messages = [...this.messages, msg];
        this.cdr.markForCheck();
        this.scrollToBottom();
      }
    });

    this.socket.typing$.pipe(takeUntil(this.destroy$)).subscribe((evt) => {
      if (evt.user_id !== this.currentUser.id) {
        this.typingUsers.set(evt.user_id, evt.name);
        this.cdr.markForCheck();
      }
    });

    this.socket.stopTyping$.pipe(takeUntil(this.destroy$)).subscribe((evt) => {
      this.typingUsers.delete(evt.user_id);
      this.cdr.markForCheck();
    });
  }

  // ── Mention autocomplete ──────────────────────────────

  private setupMentionSearch(): void {
    this.mentionSearch$
      .pipe(
        debounceTime(200),
        filter((q) => q.length >= 1),
        switchMap((q) => this.api.searchUsers(q)),
        takeUntil(this.destroy$)
      )
      .subscribe({
        next: (users) => {
          this.mentionResults = users;
          this.showMentions = users.length > 0;
          this.mentionIndex = 0;
          this.cdr.markForCheck();
        },
        error: () => {
          this.mentionResults = [];
          this.showMentions = false;
          this.cdr.markForCheck();
        },
      });
  }

  private detectMention(): void {
    const el = this.messageInput?.nativeElement;
    const cursorPos = el?.selectionStart ?? this.inputText.length;
    const textBefore = this.inputText.slice(0, cursorPos);
    const match = textBefore.match(/@(\w*)$/);

    if (match) {
      const query = match[1];
      if (query.length >= 1) {
        this.mentionSearch$.next(query);
      } else {
        this.mentionResults = [];
        this.showMentions = false;
      }
    } else {
      this.mentionResults = [];
      this.showMentions = false;
    }
  }

  insertMention(user: ChatUser): void {
    const el = this.messageInput?.nativeElement;
    const cursorPos = el?.selectionStart ?? this.inputText.length;
    const before = this.inputText.slice(0, cursorPos);
    const after = this.inputText.slice(cursorPos);
    const newBefore = before.replace(/@\w*$/, `@${user.name} `);

    this.inputText = newBefore + after;
    this.showMentions = false;
    this.mentionResults = [];
    this.cdr.markForCheck();

    setTimeout(() => el?.focus(), 0);
  }

  // ── Event handlers ────────────────────────────────────

  onInputChange(): void {
    this.detectMention();

    // Typing indicator
    this.socket.emitTyping();
    if (this.typingTimeout) clearTimeout(this.typingTimeout);
    this.typingTimeout = setTimeout(() => this.socket.emitStopTyping(), 1500);
  }

  onKeyDown(event: KeyboardEvent): void {
    // Mention navigation
    if (this.showMentions && this.mentionResults.length > 0) {
      if (event.key === 'ArrowDown') {
        event.preventDefault();
        this.mentionIndex = Math.min(
          this.mentionIndex + 1,
          this.mentionResults.length - 1
        );
        return;
      }
      if (event.key === 'ArrowUp') {
        event.preventDefault();
        this.mentionIndex = Math.max(this.mentionIndex - 1, 0);
        return;
      }
      if (event.key === 'Enter' || event.key === 'Tab') {
        event.preventDefault();
        this.insertMention(this.mentionResults[this.mentionIndex]);
        return;
      }
      if (event.key === 'Escape') {
        this.showMentions = false;
        this.mentionResults = [];
        return;
      }
    }

    // Send on Enter
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.send();
    }
  }

send(): void {
  const text = this.inputText.trim();
  if (!text || !this.conversation) return;

  const sender = (this.conversation.participants || []).find(
    (p: any) =>
      p.cflow_id === this.currentUser.cflow_id ||
      p.email === this.currentUser.email ||
      p.id === this.currentUser.id
  );

  if (!sender) {
    console.error('Sender not found in conversation participants');
    return;
  }

  this.api.sendMessage({
    conversation_id: this.conversation.id,
    sender_id: sender.id,
    message: text
  }).subscribe({
    next: (msg: any) => {
      this.messages = [...this.messages, msg];
      this.inputText = '';
      this.showMentions = false;
      this.cdr.markForCheck();
      setTimeout(() => {
        this.scrollToBottom();
        this.messageInput?.nativeElement?.focus();
      }, 0);
    },
    error: (err: any) => {
      console.error('Send message failed:', err);
    }
  });
}

  // ── Helpers ───────────────────────────────────────────

  private scrollToBottom(): void {
    setTimeout(() => {
      const el = this.scrollContainer?.nativeElement;
      if (el) el.scrollTop = el.scrollHeight;
    }, 50);
  }

  getAvatarColor(name: string): string {
    return avatarColor(name);
  }

  get typingNames(): string[] {
    return Array.from(this.typingUsers.values());
  }

  shouldShowAvatar(index: number): boolean {
    if (index === 0) return true;
    const current = this.messages[index];
    const prev = this.messages[index - 1];
    return (
      (current.sender?.id || current.sender_id) !==
      (prev.sender?.id || prev.sender_id)
    );
  }

  isOwnMessage(msg: ChatMessage): boolean {
  const sender = msg.sender;

  return !!(
    sender?.id === this.currentUser.id ||
    sender?.cflow_id === this.currentUser.cflow_id ||
    sender?.email === this.currentUser.email ||
    msg.sender_id === this.currentUser.id
  );
}

  trackByMessageId(_: number, msg: ChatMessage): string {
    return msg.id;
  }
}

<!-- Loading state -->
<div *ngIf="loading" class="loading-container">
  <div class="loading-dots">
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
  </div>
</div>

<!-- Chat panel -->
<div *ngIf="!loading" class="chat-panel">

  <!-- ── Header ──────────────────────────────────────── -->
  <div class="header">
    <div class="header-icon">
      <svg width="16" height="16" fill="none" viewBox="0 0 24 24"
           stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round"
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03
                 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512
                 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/>
      </svg>
    </div>

    <div class="header-text">
      <h2 class="header-title">
        {{ conversation?.title || 'Workflow #' + workflowId }}
      </h2>
      <span class="header-subtitle">
        {{ conversation?.participants?.length || 0 }} participants
      </span>
    </div>

    <!-- Participant avatars -->
    <div class="participant-avatars">
      <div
        *ngFor="let p of (conversation?.participants || []).slice(0, 3); let i = index"
        class="participant-avatar"
        [style.background]="getAvatarColor(p.name)"
        [style.z-index]="5 - i"
        [style.margin-left.px]="i === 0 ? 0 : -8"
        [title]="p.name"
      >
        {{ p.name.charAt(0) }}
      </div>
    </div>
  </div>

  <!-- ── Message list ────────────────────────────────── -->
  <div #scrollContainer class="message-list">

    <!-- Empty state -->
    <div *ngIf="messages.length === 0" class="empty-state">
      <svg width="48" height="48" fill="none" viewBox="0 0 24 24"
           stroke="currentColor" stroke-width="1.2" class="empty-icon">
        <path stroke-linecap="round" stroke-linejoin="round"
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03
                 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512
                 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/>
      </svg>
      <p class="empty-title">No messages yet</p>
      <p class="empty-subtitle">Start the conversation for this workflow</p>
    </div>

    <!-- Messages -->
    <cflow-message-bubble
      *ngFor="let msg of messages; let i = index; trackBy: trackByMessageId"
      [message]="msg"
      [isOwn]="isOwnMessage(msg)"
      [showAvatar]="shouldShowAvatar(i)"
    ></cflow-message-bubble>

    <!-- Typing indicator -->
    <div *ngIf="typingNames.length > 0" class="typing-indicator">
      <div class="typing-dots-sm">
        <span class="dot-sm"></span>
        <span class="dot-sm"></span>
        <span class="dot-sm"></span>
      </div>
      <span class="typing-text">
        {{ typingNames.join(', ') }}
        {{ typingNames.length === 1 ? 'is' : 'are' }} typing…
      </span>
    </div>
  </div>

  <!-- ── Input area ──────────────────────────────────── -->
  <div class="input-area">
    <!-- Mention dropdown -->
    <cflow-mention-dropdown
      *ngIf="showMentions"
      [results]="mentionResults"
      [activeIndex]="mentionIndex"
      (selectUser)="insertMention($event)"
    ></cflow-mention-dropdown>

    <div class="input-wrapper">
      <textarea
        #messageInput
        [(ngModel)]="inputText"
        (ngModelChange)="onInputChange()"
        (keydown)="onKeyDown($event)"
        placeholder="Type a message… (use @ to mention)"
        rows="1"
        class="message-textarea"
      ></textarea>

      <button
        class="send-btn"
        [class.active]="inputText.trim().length > 0"
        [disabled]="!inputText.trim()"
        (click)="send()"
      >
        <svg width="14" height="14" fill="none" viewBox="0 0 24 24"
             stroke="currentColor" stroke-width="2.5">
          <path stroke-linecap="round" stroke-linejoin="round"
                d="M5 12h14M12 5l7 7-7 7"/>
        </svg>
      </button>
    </div>
  </div>
</div>

// client/src/components/ChatWindow.jsx
import { useState, useEffect, useRef, useCallback } from "react";
import { getConversation, getMessages, searchUsers } from "../services/api";
import { useSocket } from "../hooks/useSocket";
import MessageBubble from "./MessageBubble";
import MentionDropdown from "./MentionDropdown";

// ── Avatars color palette ──────────────────────────────────
const COLORS = [
  "#3182fc", "#e74c8b", "#f59e0b", "#10b981",
  "#8b5cf6", "#ef4444", "#14b8a6", "#f97316",
];
function colorFor(name = "") {
  let hash = 0;
  for (const ch of name) hash = ch.charCodeAt(0) + ((hash << 5) - hash);
  return COLORS[Math.abs(hash) % COLORS.length];
}

export default function ChatWindow({ workflowId, currentUser }) {
  // ── State ──────────────────────────────────────────────
  const [conversation, setConversation] = useState(null);
  const [messages, setMessages]         = useState([]);
  const [input, setInput]               = useState("");
  const [loading, setLoading]           = useState(true);
  const [typingUsers, setTypingUsers]   = useState({});
  const [mentionQuery, setMentionQuery] = useState(null);
  const [mentionResults, setMentionResults] = useState([]);
  const [mentionIndex, setMentionIndex] = useState(0);

  const scrollRef  = useRef(null);
  const inputRef   = useRef(null);
  const typingTimer = useRef(null);

  // ── Load conversation + messages on mount ──────────────
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const convo = await getConversation(workflowId);
        if (cancelled) return;
        setConversation(convo);

        const msgs = await getMessages(convo.id);
        if (cancelled) return;
        setMessages(msgs);
      } catch (err) {
        console.error("Failed to load chat:", err);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [workflowId]);

  // ── Socket.io handlers ─────────────────────────────────
  const handleNewMessage = useCallback((msg) => {
    setMessages((prev) => {
      if (prev.some((m) => m.id === msg.id)) return prev;
      return [...prev, msg];
    });
  }, []);

  const handleTyping = useCallback((data) => {
    setTypingUsers((prev) => ({ ...prev, [data.user_id]: data.name }));
  }, []);

  const handleStopTyping = useCallback((data) => {
    setTypingUsers((prev) => {
      const next = { ...prev };
      delete next[data.user_id];
      return next;
    });
  }, []);

  const { sendMessage, emitTyping, emitStopTyping } = useSocket({
    workflowId,
    user: currentUser,
    onMessage: handleNewMessage,
    onTyping: handleTyping,
    onStopTyping: handleStopTyping,
  });

  // ── Auto-scroll on new messages ────────────────────────
  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages, typingUsers]);

  // ── @Mention detection ─────────────────────────────────
  useEffect(() => {
    const cursorPos = inputRef.current?.selectionStart ?? input.length;
    const textBefore = input.slice(0, cursorPos);
    const mentionMatch = textBefore.match(/@(\w*)$/);

    if (mentionMatch) {
      const query = mentionMatch[1];
      setMentionQuery(query);
      setMentionIndex(0);
      if (query.length >= 1) {
        searchUsers(query).then(setMentionResults).catch(() => setMentionResults([]));
      } else {
        setMentionResults([]);
      }
    } else {
      setMentionQuery(null);
      setMentionResults([]);
    }
  }, [input]);

  // ── Insert mention into input ──────────────────────────
  const insertMention = (user) => {
    const cursorPos = inputRef.current?.selectionStart ?? input.length;
    const textBefore = input.slice(0, cursorPos);
    const textAfter  = input.slice(cursorPos);
    const newBefore  = textBefore.replace(/@\w*$/, `@${user.name} `);
    setInput(newBefore + textAfter);
    setMentionQuery(null);
    setMentionResults([]);
    setTimeout(() => inputRef.current?.focus(), 0);
  };

  // ── Send ───────────────────────────────────────────────
  const handleSend = () => {
    const text = input.trim();
    if (!text) return;
    sendMessage(text);
    setInput("");
    emitStopTyping();
    inputRef.current?.focus();
  };

  // ── Typing indicator (debounced) ───────────────────────
  const handleInputChange = (e) => {
    setInput(e.target.value);
    emitTyping();
    clearTimeout(typingTimer.current);
    typingTimer.current = setTimeout(() => emitStopTyping(), 1500);
  };

  // ── Key handling ───────────────────────────────────────
  const handleKeyDown = (e) => {
    // Mention navigation
    if (mentionResults.length > 0) {
      if (e.key === "ArrowDown") {
        e.preventDefault();
        setMentionIndex((i) => Math.min(i + 1, mentionResults.length - 1));
        return;
      }
      if (e.key === "ArrowUp") {
        e.preventDefault();
        setMentionIndex((i) => Math.max(i - 1, 0));
        return;
      }
      if (e.key === "Enter" || e.key === "Tab") {
        e.preventDefault();
        insertMention(mentionResults[mentionIndex]);
        return;
      }
      if (e.key === "Escape") {
        setMentionQuery(null);
        setMentionResults([]);
        return;
      }
    }

    // Normal enter → send
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  // ── Derived data ───────────────────────────────────────
  const typingNames = Object.values(typingUsers).filter(
    (n) => n !== currentUser.name
  );

  // ── Loading state ──────────────────────────────────────
  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="flex gap-1.5">
          <span className="typing-dot w-2.5 h-2.5 rounded-full bg-cflow-400" />
          <span className="typing-dot w-2.5 h-2.5 rounded-full bg-cflow-400" />
          <span className="typing-dot w-2.5 h-2.5 rounded-full bg-cflow-400" />
        </div>
      </div>
    );
  }

  // ── Render ─────────────────────────────────────────────
  return (
    <div className="flex flex-col h-full bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
      {/* ── Header ──────────────────────────────── */}
      <div className="flex items-center gap-3 px-5 py-3.5 border-b border-gray-100 bg-gradient-to-r from-cflow-600 to-cflow-700">
        <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-white/20 text-white">
          <svg width="18" height="18" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
        </div>
        <div className="flex-1 min-w-0">
          <h2 className="text-sm font-semibold text-white truncate">
            {conversation?.title || `Workflow #${workflowId}`}
          </h2>
          <p className="text-[11px] text-white/60">
            {conversation?.participants?.length || 0} participants
          </p>
        </div>
        {/* Participant avatars */}
        <div className="flex -space-x-2">
          {(conversation?.participants || []).slice(0, 5).map((p) => (
            <div
              key={p.id}
              title={p.name}
              className="w-7 h-7 rounded-full border-2 border-cflow-700 flex items-center justify-center text-[10px] font-bold text-white uppercase"
              style={{ backgroundColor: colorFor(p.name) }}
            >
              {p.name?.[0]}
            </div>
          ))}
        </div>
      </div>

      {/* ── Messages ────────────────────────────── */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto chat-scroll px-5 py-4 space-y-1">
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full text-gray-400 select-none">
            <svg width="48" height="48" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.2" className="mb-3 text-gray-300">
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
            </svg>
            <p className="text-sm font-medium">No messages yet</p>
            <p className="text-xs mt-0.5">Start the conversation for this workflow</p>
          </div>
        )}

        {messages.map((msg, idx) => {
          const isOwn     = msg.sender?.id === currentUser.id || msg.sender_id === currentUser.id;
          const prevMsg   = messages[idx - 1];
          const sameSender = prevMsg && (prevMsg.sender?.id || prevMsg.sender_id) === (msg.sender?.id || msg.sender_id);
          const showAvatar = !sameSender;

          return (
            <MessageBubble
              key={msg.id}
              message={msg}
              isOwn={isOwn}
              showAvatar={showAvatar}
              colorFor={colorFor}
            />
          );
        })}

        {/* Typing indicator */}
        {typingNames.length > 0 && (
          <div className="flex items-center gap-2 pt-1 pl-10">
            <div className="flex gap-1">
              <span className="typing-dot w-1.5 h-1.5 rounded-full bg-gray-400" />
              <span className="typing-dot w-1.5 h-1.5 rounded-full bg-gray-400" />
              <span className="typing-dot w-1.5 h-1.5 rounded-full bg-gray-400" />
            </div>
            <span className="text-xs text-gray-400">
              {typingNames.join(", ")} {typingNames.length === 1 ? "is" : "are"} typing…
            </span>
          </div>
        )}
      </div>

      {/* ── Input ───────────────────────────────── */}
      <div className="relative px-4 pb-4 pt-2">
        {/* Mention autocomplete dropdown */}
        {mentionResults.length > 0 && (
          <MentionDropdown
            results={mentionResults}
            activeIndex={mentionIndex}
            onSelect={insertMention}
            colorFor={colorFor}
          />
        )}

        <div className="flex items-end gap-2 bg-gray-50 rounded-xl border border-gray-200 px-3 py-2 focus-within:border-cflow-400 focus-within:ring-2 focus-within:ring-cflow-100 transition-all">
          <textarea
            ref={inputRef}
            value={input}
            onChange={handleInputChange}
            onKeyDown={handleKeyDown}
            placeholder="Type a message… (use @ to mention)"
            rows={1}
            className="flex-1 bg-transparent resize-none text-sm text-gray-800 placeholder-gray-400 outline-none max-h-28 leading-relaxed"
            style={{ minHeight: "24px" }}
          />
          <button
            onClick={handleSend}
            disabled={!input.trim()}
            className="flex items-center justify-center w-8 h-8 rounded-lg bg-cflow-600 text-white hover:bg-cflow-700 disabled:opacity-30 disabled:cursor-not-allowed transition-colors shrink-0"
          >
            <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 12h14M12 5l7 7-7 7" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}
